# Ignore Phoenix.LiveView.JS opaque contract noise from JS.dispatch/push helpers.
# Specs correctly return Phoenix.LiveView.JS.t(); Dialyzer still sees the struct shape.
[
  {"lib/components/accordion.ex", :contract_with_opaque},
  {"lib/components/accordion/connect.ex", :contract_with_opaque},
  {"lib/components/angle_slider.ex", :contract_with_opaque},
  {"lib/components/avatar.ex", :contract_with_opaque},
  {"lib/components/carousel.ex", :contract_with_opaque},
  {"lib/components/clipboard.ex", :contract_with_opaque},
  {"lib/components/collapsible.ex", :contract_with_opaque},
  {"lib/components/color_picker.ex", :contract_with_opaque},
  {"lib/components/combobox.ex", :contract_with_opaque},
  {"lib/components/date_picker.ex", :contract_with_opaque},
  {"lib/components/date_picker/connect.ex", :contract_with_opaque},
  {"lib/components/dialog.ex", :contract_with_opaque},
  {"lib/components/editable.ex", :contract_with_opaque},
  {"lib/components/file_upload.ex", :contract_with_opaque},
  {"lib/components/floating_panel.ex", :contract_with_opaque},
  {"lib/components/listbox.ex", :contract_with_opaque},
  {"lib/components/marquee.ex", :contract_with_opaque},
  {"lib/components/marquee/connect.ex", :contract_with_opaque},
  {"lib/components/menu.ex", :contract_with_opaque},
  {"lib/components/menu/connect.ex", :contract_with_opaque},
  {"lib/components/native_accordion.ex", :contract_with_opaque},
  {"lib/components/native_accordion/js.ex", :contract_with_opaque},
  {"lib/components/number_input.ex", :contract_with_opaque},
  {"lib/components/pagination.ex", :contract_with_opaque},
  {"lib/components/password_input.ex", :contract_with_opaque},
  {"lib/components/pin_input.ex", :contract_with_opaque},
  {"lib/components/radio_group.ex", :contract_with_opaque},
  {"lib/components/select.ex", :contract_with_opaque},
  {"lib/components/signature_pad.ex", :contract_with_opaque},
  {"lib/components/slider.ex", :contract_with_opaque},
  {"lib/components/switch.ex", :contract_with_opaque},
  {"lib/components/tabs.ex", :contract_with_opaque},
  {"lib/components/tags_input.ex", :contract_with_opaque},
  {"lib/components/timer.ex", :contract_with_opaque},
  {"lib/components/toast.ex", :contract_with_opaque},
  {"lib/components/toast/connect.ex", :contract_with_opaque},
  {"lib/components/toggle.ex", :contract_with_opaque},
  {"lib/components/toggle_group.ex", :contract_with_opaque},
  {"lib/components/tooltip.ex", :contract_with_opaque},
  {"lib/corex/api/respond_to.ex", :contract_with_opaque},
]
