defmodule Corex.ComponentHelpersCoverageTest do
  use CorexTest.ComponentCase, async: true

  alias CorexTest.ComponentHelpers, as: H

  @helpers [
    {:render_accordion, %{}},
    {:render_accordion_with_indicator, %{}},
    {:render_accordion_with_custom_slots, %{}},
    {:render_avatar, %{}},
    {:render_carousel, %{}},
    {:render_checkbox, %{}},
    {:render_clipboard, %{}},
    {:render_collapsible, %{}},
    {:render_collapsible_with_closed_surface, %{}},
    {:render_collapsible_with_let_slots, %{}},
    {:render_combobox, %{}},
    {:render_combobox_with_items, %{}},
    {:render_combobox_with_item_slot, %{}},
    {:render_combobox_with_clear_and_indicator, %{}},
    {:render_combobox_grouped, %{}},
    {:render_combobox_filter_false, %{}},
    {:render_combobox_default_multiple, %{}},
    {:render_combobox_with_errors, %{}},
    {:render_date_picker, %{}},
    {:render_color_picker, %{}},
    {:render_dialog, %{}},
    {:render_dialog_nested_slots, %{}},
    {:render_dialog_controlled, %{}},
    {:render_editable, %{}},
    {:render_editable_with_translation, %{translation: %Corex.Editable.Translation{}}},
    {:render_floating_panel, %{}},
    {:render_floating_panel_without_stage_triggers, %{}},
    {:render_listbox, %{}},
    {:render_listbox_grouped, %{}},
    {:render_listbox_list_items, %{}},
    {:render_listbox_controlled, %{}},
    {:render_marquee, %{}},
    {:render_menu, %{}},
    {:render_menu_grouped, %{}},
    {:render_menu_nested, %{}},
    {:render_menu_with_loading, %{}},
    {:render_select, %{}},
    {:render_select_with_opts, %{placeholder: "Pick one"}},
    {:render_select_controlled_multiple, %{}},
    {:render_select_grouped, %{}},
    {:render_select_uncontrolled_value, %{}},
    {:render_select_with_field, %{}},
    {:render_tabs, %{}},
    {:render_tabs_with_indicator, %{}},
    {:render_tabs_items_with_custom_slots, %{}},
    {:render_timer, %{}},
    {:render_timer_paused, %{}},
    {:render_signature_pad, %{}},
    {:render_switch, %{}},
    {:render_signature_pad_controlled, %{}},
    {:render_signature_pad_drawing_opts, %{}},
    {:render_signature_pad_on_draw_end, %{}},
    {:render_signature_pad_with_field, %{}},
    {:render_signature_pad_with_paths, %{paths: []}},
    {:render_signature_pad_with_errors, %{}},
    {:render_toggle, %{}},
    {:render_tags_input, %{}},
    {:render_pagination, %{}},
    {:render_pagination_link_patch, %{}},
    {:render_toggle_group, %{}},
    {:render_tree_view, %{}},
    {:render_tree_view_with_branch, %{}},
    {:render_tree_view_with_defaults, %{}},
    {:render_action, %{}},
    {:render_action_with_opts, %{type: "button", aria_label: "Save", disabled: false}},
    {:render_navigate,
     %{to: "/x", type: "href", external: false, download: nil, aria_label: "Go"}},
    {:render_navigate_with_replace, %{to: "/y"}},
    {:render_navigate_with_method, %{to: "/z"}},
    {:render_file_upload_minimal, %{}},
    {:render_file_upload_full, %{}},
    {:render_file_upload_with_field, %{}},
    {:render_file_upload_with_close, %{}},
    {:render_file_upload_live_minimal, %{}},
    {:render_password_input_full, %{}},
    {:render_password_input_with_field, %{}},
    {:render_radio_group_with_indicator, %{}},
    {:render_radio_group_controlled, %{}},
    {:render_radio_group_with_item_slot, %{}},
    {:render_radio_group_with_form, %{}}
  ]

  test "renders all component helpers" do
    for {helper, assigns} <- @helpers do
      fun = fn a -> apply(H, helper, [a]) end
      html = render_component(fun, assigns)
      assert byte_size(to_string(html)) > 0, "expected HTML from #{helper}"
    end
  end
end
