defmodule CorexAdmin.Resource.Spec do
  @moduledoc """
  The compiled form of a resource module.

  This is the value every other layer reads: controllers, UI blocks, the export
  controller, and any host LiveView generated by
  `mix corex.admin.gen.live`. It is **public API** — a host that composes its own
  chrome receives a spec in `@spec` and may pattern match on it.

  Build one with `resource_module.__corex_admin_resource__/0`.
  """

  alias CorexAdmin.Resource.{Field, Filter, Section}

  @enforce_keys [:module, :context, :schema, :slug, :label, :actions, :fields]
  defstruct [
    :module,
    :context,
    :schema,
    :slug,
    :group,
    :label,
    :singular,
    :scope,
    :primary_key,
    :page_size,
    :page_size_options,
    :default_sort,
    :title_field,
    :history,
    live: %{},
    history_opts: [],
    selectable: true,
    default_filters: %{},
    actions: %{},
    collection_actions: [],
    bulk_actions: [],
    record_actions: [],
    fields: [],
    filters: [],
    form_sections: [],
    show_sections: []
  ]

  @type t :: %__MODULE__{
          module: module(),
          context: module(),
          schema: module(),
          slug: String.t(),
          group: String.t() | nil,
          label: String.t(),
          singular: String.t(),
          scope: atom() | nil,
          primary_key: atom(),
          page_size: pos_integer() | nil,
          page_size_options: [pos_integer()] | nil,
          default_sort: {atom(), :asc | :desc} | nil,
          title_field: atom() | nil,
          history: module() | nil,
          live: %{optional(:index | :show | :form) => module()},
          history_opts: keyword(),
          selectable: boolean(),
          default_filters: map(),
          actions: %{atom() => atom()},
          collection_actions: [module()],
          bulk_actions: [module()],
          record_actions: [module()],
          fields: [Field.t()],
          filters: [Filter.t()],
          form_sections: [Section.t()],
          show_sections: [Section.t()]
        }

  @doc "Field by name, or nil."
  @spec field(t(), atom()) :: Field.t() | nil
  def field(%__MODULE__{fields: fields}, name) do
    Enum.find(fields, &(&1.name == name))
  end

  @doc "Filter by name, or nil."
  @spec filter(t(), atom()) :: Filter.t() | nil
  def filter(%__MODULE__{filters: filters}, name) do
    Enum.find(filters, &(&1.name == name))
  end

  @doc "Fields that point at another resource."
  @spec relations(t()) :: [Field.t()]
  def relations(%__MODULE__{fields: fields}), do: Enum.filter(fields, &Field.relation?/1)

  @doc "Whether the resource declared a Phoenix scope."
  @spec scoped?(t()) :: boolean()
  def scoped?(%__MODULE__{scope: scope}), do: not is_nil(scope)
end
